
package com.ticketbooking.app.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TicketService", targetNamespace = "http://service.app.ticketbooking.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TicketService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.ticketbooking.app.service.TicketDetails
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.app.ticketbooking.com/TicketService/getTicketRequest", output = "http://service.app.ticketbooking.com/TicketService/getTicketResponse")
    public TicketDetails getTicket(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.app.ticketbooking.com/TicketService/createTicketRequest", output = "http://service.app.ticketbooking.com/TicketService/createTicketResponse")
    public long createTicket(
        @WebParam(name = "arg0", partName = "arg0")
        TicketDetails arg0);

    /**
     * 
     * @return
     *     returns com.ticketbooking.app.service.TicketDetailsArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.app.ticketbooking.com/TicketService/getAllTicketsRequest", output = "http://service.app.ticketbooking.com/TicketService/getAllTicketsResponse")
    public TicketDetailsArray getAllTickets();

}
